Revert "FROMLIST: PM / devfreq: Add new target_freq attribute flag for governors"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 8778df9c6399f1de923627ac8dcfa8b85e6cb8eb.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>