Revert "FROMLIST: PM / devfreq: Add a governor for tracking remote device frequencies"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 24d900755ba57a5bc8265727fd056ab120feac50.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>