Revert "QCLINUX: qcom.config: Enable QCOM SCMI memlat bus scaling"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit c98079e37777f50236879c5b708ced5d7549ce2e.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>