Revert "UPSTREAM: of: Add wrappers to match root node with OF device ID tables"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 813b17a7e47c84bbdc4ce4f8f2e8a6947d02eec9.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>