Revert "UPSTREAM: of: Add of_machine_get_match() helper"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 863c23780bcf87124e8bc097ce5c4e2ced0429e0.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>