Revert "FROMLIST: arm64: dts: qcom: hamoa: Enable LLCC/DDR/DDR_QOS dvfs"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 49ba4fbb0aed18305afd73709f3882d6f4c5127a.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>