Revert "FROMGIT: firmware: arm_scmi: Rework protocol version negotiation logic"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit e8c65617b88706dd97594b640893291ad3e8adf2.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>