Revert "FROMLIST: firmware: arm_scmi: Add QCOM Generic Vendor Protocol documentation"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 61aa22d5730f3972095d8bba13629ed8d76d6134.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>