Revert "FROMLIST: PM / devfreq: Introduce the QCOM SCMI Memlat devfreq device"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit ebce65aecbb4a05b95bf48989d80e6d1b2687078.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>