Revert "FROMLIST: firmware: arm_scmi: vendors: Add QCOM SCMI Generic Extensions"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 79844e58c53189873f93e1d0c9dfa165e9017126.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>