Revert "FROMGIT: PM / devfreq: Move governor.h to a public header location"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 6df46fd1d1b5f013bef6383b19ec712b7e1dbc76.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>