Revert "FROMGIT: of: Convert to of_machine_get_match()"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 98bf838e6981137d8184c9793daa1b5347743d80.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>