Revert "FROMLIST: PM / devfreq: Add new track_remote flag for governors"
Out of tree module compilation is failing as this series moves the governor.h header.

INFO - | governor_gpubw_mon.c:14:10: fatal error: governor.h: No such file or directory
INFO - | 14 | #include "governor.h"

Reverting the series for now, and will be brought back with proper fix.

This reverts commit 6f442d4c3d7b2a4901bc974343e2186fa31c7d8b.

Signed-off-by: Salendarsingh Gaud <sgaud@qti.qualcomm.com>